"""Pydantic models for structured outputs and pipeline data structures."""

from enum import Enum
from pathlib import Path
from typing import List, Optional
from pydantic import BaseModel, Field


class VideoQuality(str, Enum):
    LOW = "low"          # 480p (854x480)
    MEDIUM = "medium"    # 720p (1280x720)
    HIGH = "high"        # 1080p (1920x1080)
    FOUR_K = "4k"        # 2160p (3840x2160)


class AspectRatio(str, Enum):
    WIDESCREEN = "16:9"  # 1920x1080 default
    VERTICAL = "9:16"    # 1080x1920 for YouTube Shorts / TikTok / Reels


class SceneVisualConcept(BaseModel):
    """Visual elements and animation ideas for a single scene."""
    description: str = Field(
        description="Detailed visual description of what should be drawn, animated, or transformed."
    )
    math_formulas: List[str] = Field(
        default_factory=list,
        description="LaTeX formulas or equations to display on screen (e.g. r'a^2 + b^2 = c^2')."
    )
    geometric_elements: List[str] = Field(
        default_factory=list,
        description="Shapes, graphs, vectors, coordinate systems, or diagrams to construct."
    )
    color_palette: List[str] = Field(
        default_factory=list,
        description="Dominant colors or highlights used (e.g. ['BLUE', 'YELLOW', 'WHITE'])."
    )
    camera_and_focus: Optional[str] = Field(
        default="Center focus with balanced margins",
        description="Camera motion, zoom, or framing instructions."
    )


class ScenePlan(BaseModel):
    """A pedagogical scene in the overall storyboard."""
    scene_number: int = Field(description="Sequential index of the scene, starting from 1.")
    scene_title: str = Field(description="Short, descriptive title for this scene.")
    narration: str = Field(
        description="Exact spoken voiceover narration script. Must be clear, engaging, and educational."
    )
    visuals: SceneVisualConcept = Field(
        description="Structured visual blueprint and animation concept for this scene."
    )
    estimated_duration_sec: float = Field(
        default=10.0,
        description="Rough estimated duration in seconds for planning."
    )


class Storyboard(BaseModel):
    """Structured educational storyboard generated by Gemini."""
    topic: str = Field(description="The STEM topic being taught.")
    target_audience: str = Field(
        default="General STEM Students / Enthusiasts",
        description="Target educational audience and difficulty level."
    )
    overall_theme: str = Field(
        default="Clear, intuitive, visual explanation with mathematical rigor.",
        description="Stylistic and pedagogical tone of the video."
    )
    learning_objectives: List[str] = Field(
        default_factory=list,
        description="Key takeaways and concepts the viewer will master."
    )
    scenes: List[ScenePlan] = Field(
        description="Ordered list of pedagogical scenes forming a complete cohesive video."
    )


class SceneAudioResult(BaseModel):
    """Audio generation outcome for a scene."""
    scene_number: int
    audio_path: Path
    duration_sec: float
    voice: str


class ManimCodeResult(BaseModel):
    """Generated Manim Python code for a scene."""
    scene_number: int
    scene_class_name: str
    code: str
    target_duration_sec: float


class RenderAttempt(BaseModel):
    """Record of a single Manim rendering attempt in the self-healing loop."""
    attempt_number: int
    code: str
    success: bool
    error_message: Optional[str] = None
    output_video_path: Optional[Path] = None
    render_duration_sec: Optional[float] = None


class SceneRenderResult(BaseModel):
    """Final outcome of rendering a scene with Manim."""
    scene_number: int
    scene_title: str
    scene_class_name: str
    code_path: Path
    raw_video_path: Path
    synced_video_path: Optional[Path] = None
    audio_path: Optional[Path] = None
    target_duration_sec: float
    actual_duration_sec: float
    attempts: int
    is_success: bool
    error_log: Optional[str] = None


class TokenUsage(BaseModel):
    """Aggregate token usage tracking for Gemini API calls."""
    prompt_tokens: int = 0
    candidates_tokens: int = 0
    total_tokens: int = 0
    api_calls: int = 0


class PipelineResult(BaseModel):
    """Final output summary of the full video generation pipeline."""
    topic: str
    storyboard: Storyboard
    scenes_rendered: List[SceneRenderResult]
    final_video_path: Optional[Path] = None
    total_duration_sec: float = 0.0
    output_dir: Path
    is_success: bool
    error_summary: Optional[str] = None
    token_usage: Optional[TokenUsage] = None
